# fly.toml app configuration file generated for aged-breeze-5072 on 2023-10-04T11:40:13-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aged-breeze-5072"
primary_region = "gru"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
